export enum ENUM_IT_STRINGS {
    language = "Lingua",
    privacyNotice = "Prendi un momento per consultare la nostra normativa sulla privacy prima di rispondere a questo questionario",
    startButtonText = "Inizia",
    sendButtonText = "invia",
    skipButtonText = "salta",
    restartButtonText = "Ricomincia",
    continueButtonText = "Continua",
    endButtonText = "Fatto",
    endScreenButtonText = "Mostra chat",
    doneConversation = "Sembra che stessimo già avendo questa conversazione...",
    endScreenText = "Ora puoi chiudere questa pagina 😊",
    consentText = "*premendo su INIZIA, confermi di essere informato e di voler rispondere alle domande di questo questionario.",
    cookieText = "Ciao! Vorremmo usare dei cookie per migliorare la tua esperienza, ma ci serve il tuo consenso per farlo",
    readMoreButtonText = "Leggi di più",
    cookieAgreeButton = "Accetta",
    wrongLinkText = "Ci spiace, il link è scaduto oppure incompleto.",
    unableToLoadChatText = "Impossibile caricare la chat, il link è scaduro oppure incompleto.",
    somethingWrongText = "Qualcosa è andato storto...",
    noSurveyChosenText = "Nessuna conversatione selezionata",
    surveyAlreadyCompetedText = "Hai già compilato questo questionario",
    noPublishedSurvey = "Mi spiace, non ho trovato nessun questionario disponibile",
}

export enum ENUM_EN_STRINGS {
    language = "Language",
    privacyNotice = "Please take a moment to review our policy prior to answering the survey questions",
    startButtonText = "Start",
    sendButtonText = "send",
    skipButtonText = "skip",
    restartButtonText = "Restart",
    continueButtonText = "Continue",
    endButtonText = "Done",
    endScreenButtonText = "Show Chat",
    doneConversation = "It looks like we were already having this conversation...",
    endScreenText = "You can now close this page 😊",
    consentText = "*by clicking START, you consent that you are informed and willing to answer the questions in this survey.",
    cookieText = "Hi! We'd like to use cookies to enhance your experience, but we need your consent to do so.",
    readMoreButtonText = "Read More",
    cookieAgreeButton = "Agree",
    wrongLinkText = "Sorry, either the link is expired or is missing some information...",
    unableToLoadChatText = "Couldn't load the chat. Either the link is expired or is missing some information...",
    somethingWrongText = "Something went wrong...",
    noSurveyChosenText = "No survey was chosen",
    surveyAlreadyCompetedText = "You have already completed this survey",
    noPublishedSurvey = "Sorry, I couldn't find any available surveys",
}

export enum ENUM_FR_STRINGS {
    language = "Langue",
    privacyNotice = "S'il vous plaît, prenez un moment pour lire les politiques préalables à la participation des questionnaires",
    startButtonText = "Commencer",
    sendButtonText = "valider",
    skipButtonText = "suivant",
    restartButtonText = "Recommencer",
    continueButtonText = "Continuer",
    endButtonText = "Fin",
    endScreenButtonText = "Show Chat",
    doneConversation = "Il semble que nous avons déjà eu cette conversation ...",
    endScreenText = "Tu peux fermer la page maintenant  😊",
    consentText = "*en cliquant sur commencer, vous concenter d'être informé et de répondre aux questions de cette enquête.",
    cookieText = "Hi! We'd like to use cookies to enhance your experience, but we need your consent to do so.",
    readMoreButtonText = "Read More",
    cookieAgreeButton = "Agree",
    wrongLinkText = "Sorry, either the link is expired or is missing some information...",
    unableToLoadChatText = "Couldn't load the chat. Either the link is expired or is missing some information...",
    somethingWrongText = "Something went wrong...",
    noSurveyChosenText = "No survey was chosen",
    surveyAlreadyCompetedText = "You have already completed this survey",
    noPublishedSurvey = "Sorry, I couldn't find any available surveys",
}

export enum ENUM_EL_STRINGS {
    language = "Γλώσσα",
    privacyNotice = "Σας παρακαλώ αφιερώστε λίγο χρόνο για να ελέγξετε την πολιτική μας πριν απαντήσετε στις ερωτήσεις της έρευνας",
    startButtonText = "Αρχή",
    sendButtonText = "invia",
    skipButtonText = "salta",
    restartButtonText = "επανεκκίνηση",
    continueButtonText = "να συνεχίσει",
    endButtonText = "Fatto",
    endScreenButtonText = "Mostra chat",
    doneConversation = "Φαίνεται ότι είχαμε ήδη αυτή τη μετατροπή ...",
    endScreenText = "Τώρα μπορείς να κλείσεις τη σελίδα 😊",
    consentText = "* Επιλέγοντας ΑΡΧΗ, αποδέχεστε ότι είστε ενημερωμένοι και πρόθυμοι να απαντήσετε στις ερωτήσεις αυτής της έρευνας",
    cookieText = "Hi! We'd like to use cookies to enhance your experience, but we need your consent to do so.",
    readMoreButtonText = "Read More",
    cookieAgreeButton = "Agree",
    wrongLinkText = "Sorry, either the link is expired or is missing some information...",
    unableToLoadChatText = "Couldn't load the chat. Either the link is expired or is missing some information...",
    somethingWrongText = "Something went wrong...",
    noSurveyChosenText = "No survey was chosen",
    surveyAlreadyCompetedText = "You have already completed this survey",
    noPublishedSurvey = "Sorry, I couldn't find any available surveys",
}

export enum ENUM_FI_STRINGS {
    language = "Kieli",
    privacyNotice = "Ennen kuin vastaat kysymyksiin, luethan ensin toimintatavoistamme",
    startButtonText = "Aloita",
    sendButtonText = "send",
    skipButtonText = "skip",
    restartButtonText = "Aloita uudelleen",
    continueButtonText = "Jatka",
    endButtonText = "Done",
    endScreenButtonText = "Show Chat",
    doneConversation = "It looks like we were already having this conversation...",
    endScreenText = "Voit nyt sulkea tämän sivun 😊",
    consentText = "*painamalla ALOITA hyväksyt, että haluat vastata kysymyksiin.",
    cookieText = "Hi! We'd like to use cookies to enhance your experience, but we need your consent to do so.",
    readMoreButtonText = "Read More",
    cookieAgreeButton = "Agree",
    wrongLinkText = "Sorry, either the link is expired or is missing some information...",
    unableToLoadChatText = "Couldn't load the chat. Either the link is expired or is missing some information...",
    somethingWrongText = "Something went wrong...",
    noSurveyChosenText = "No survey was chosen",
    surveyAlreadyCompetedText = "You have already completed this survey",
    noPublishedSurvey = "Sorry, I couldn't find any available surveys",
}

export enum ENUM_SK_STRINGS {
    language = "Jazyk",
    privacyNotice = "Predtým než začnete odpovedať na otázky pozrite si prosím naše zásady",
    startButtonText = "Štart",
    sendButtonText = "send",
    skipButtonText = "skip",
    restartButtonText = "Začať znova",
    continueButtonText = "Pokračovať",
    endButtonText = "Done",
    endScreenButtonText = "Show Chat",
    doneConversation = "Vyzerá to, že o tomto sme sa už bavili...",
    endScreenText = "Teraz môžete túto stránku zavrieť 😊",
    consentText = "* kliknutím na ŠTART vyjadrujete súhlas, že ste informovaní a chcete odpovedať na otázky",
    cookieText = "Hi! We'd like to use cookies to enhance your experience, but we need your consent to do so.",
    readMoreButtonText = "Read More",
    cookieAgreeButton = "Agree",
    wrongLinkText = "Sorry, either the link is expired or is missing some information...",
    unableToLoadChatText = "Couldn't load the chat. Either the link is expired or is missing some information...",
    somethingWrongText = "Something went wrong...",
    noSurveyChosenText = "No survey was chosen",
    surveyAlreadyCompetedText = "You have already completed this survey",
    noPublishedSurvey = "Sorry, I couldn't find any available surveys",
}

export enum ENUM_CS_STRINGS {
    language = "Jazyk",
    privacyNotice = "PNež odpovíte na otázky v průzkumu, věnujte prosím chvilku kontrole našich zásad",
    startButtonText = "Start",
    sendButtonText = "send",
    skipButtonText = "skip",
    restartButtonText = "Začít znovu",
    continueButtonText = "Pokračovat",
    endButtonText = "Done",
    endScreenButtonText = "Show Chat",
    doneConversation = "Vypadá to, že jsme už tuto konverzaci vedli...",
    endScreenText = "Nyní můžete tuto stránku zavřít. 😊",
    consentText = "* kliknutím na START souhlasíte, že jste informováni a ochotni odpovědět na otázky v tomto průzkumu.",
    cookieText = "Hi! We'd like to use cookies to enhance your experience, but we need your consent to do so.",
    readMoreButtonText = "Read More",
    cookieAgreeButton = "Agree",
    wrongLinkText = "Sorry, either the link is expired or is missing some information...",
    unableToLoadChatText = "Couldn't load the chat. Either the link is expired or is missing some information...",
    somethingWrongText = "Something went wrong...",
    noSurveyChosenText = "No survey was chosen",
    surveyAlreadyCompetedText = "You have already completed this survey",
    noPublishedSurvey = "Sorry, I couldn't find any available surveys",
}

export enum ENUM_ES_STRINGS {
    language = "Idioma",
    privacyNotice = "Por favor, tómete un momento para revisar nuestra política antes de responder a las preguntas de la encuesta",
    startButtonText = "Inicia",
    sendButtonText = "invia",
    skipButtonText = "salta",
    restartButtonText = "Reiniciar",
    continueButtonText = "Continuar",
    endButtonText = "Fatto",
    endScreenButtonText = "Mostra chat",
    doneConversation = "Parece que ya estábamos teniendo esta conversación...",
    endScreenText = "Ahora puedes cerrar esta página 😊",
    consentText = "*al hacer clic en INICIA, consientes que estás informado y dispuesto a responder a las preguntas de esta encuesta.",
    cookieText = "Hi! We'd like to use cookies to enhance your experience, but we need your consent to do so.",
    readMoreButtonText = "Read More",
    cookieAgreeButton = "Agree",
    wrongLinkText = "Sorry, either the link is expired or is missing some information...",
    unableToLoadChatText = "Couldn't load the chat. Either the link is expired or is missing some information...",
    somethingWrongText = "Something went wrong...",
    noSurveyChosenText = "No survey was chosen",
    surveyAlreadyCompetedText = "You have already completed this survey",
    noPublishedSurvey = "Sorry, I couldn't find any available surveys",
}

export enum ENUM_DE_STRINGS {
    language = "Sprache",
    privacyNotice = "Bitte nehmen Sie sich vor der Beantwortung der Fragen einen Augenblick Zeit, um unsere Richtlinien zu prüfen.",
    startButtonText = "Start",
    sendButtonText = "send",
    skipButtonText = "skip",
    restartButtonText = "Neu starten",
    continueButtonText = "Fortfahren",
    endButtonText = "Done",
    endScreenButtonText = "Show Chat",
    doneConversation = "Es sieht so aus, als hätten wir uns darüber schon unterhalten...",
    endScreenText = "Sie können diese Seite nun schließen 😊",
    consentText = "*durch Klicken auf START bestätigen Sie, dass Sie informiert wurden und bereit sind, die Fragen der Umfrage zu beantworten.",
    cookieText = "Hi! We'd like to use cookies to enhance your experience, but we need your consent to do so.",
    readMoreButtonText = "Read More",
    cookieAgreeButton = "Agree",
    wrongLinkText = "Sorry, either the link is expired or is missing some information...",
    unableToLoadChatText = "Couldn't load the chat. Either the link is expired or is missing some information...",
    somethingWrongText = "Something went wrong...",
    noSurveyChosenText = "No survey was chosen",
    surveyAlreadyCompetedText = "You have already completed this survey",
    noPublishedSurvey = "Sorry, I couldn't find any available surveys",
}

export enum ENUM_UK_STRINGS {
    language = "Мова",
    privacyNotice = "Будь ласка, знайдіть час, щоб ознайомитися з нашими вказівками, перш ніж відповідати на питання опитування.",
    startButtonText = "Старт",
    sendButtonText = "send",
    skipButtonText = "skip",
    restartButtonText = "Перезапустити",
    continueButtonText = "Продовжувати",
    endButtonText = "Done",
    endScreenButtonText = "Show Chat",
    doneConversation = "Схоже, ми вже вели цю розмову ...",
    endScreenText = "Тепер ви можете закрити цю сторінку 😊",
    consentText = "* натиснувши кнопку Старт, ви погоджуєтесь, що ви отримаєте інформацію та готові відповісти на питання цього опитування.",
    cookieText = "Hi! We'd like to use cookies to enhance your experience, but we need your consent to do so.",
    readMoreButtonText = "Read More",
    cookieAgreeButton = "Agree",
    wrongLinkText = "Sorry, either the link is expired or is missing some information...",
    unableToLoadChatText = "Couldn't load the chat. Either the link is expired or is missing some information...",
    somethingWrongText = "Something went wrong...",
    noSurveyChosenText = "No survey was chosen",
    surveyAlreadyCompetedText = "You have already completed this survey",
    noPublishedSurvey = "Sorry, I couldn't find any available surveys",
}

export enum ENUM_HR_STRINGS {
    language = "Jezik",
    privacyNotice = "Molim te pročitaj naša pravila prije nego počneš odgovarati na anketu.",
    startButtonText = "Start",
    sendButtonText = "send",
    skipButtonText = "skip",
    restartButtonText = "Restart",
    continueButtonText = "Nastavi",
    endButtonText = "Done",
    endScreenButtonText = "Show Chat",
    doneConversation = "Izgleda da smo već imali ovaj razgovor ...",
    endScreenText = "Sada možeš zatvoriti ovu stranicu 😊",
    consentText = "*klik na START znači tvoju suglasnost da si informiran i voljan odgovoriti na pitanja iz ankete.",
    cookieText = "Hi! We'd like to use cookies to enhance your experience, but we need your consent to do so.",
    readMoreButtonText = "Read More",
    cookieAgreeButton = "Agree",
    wrongLinkText = "Sorry, either the link is expired or is missing some information...",
    unableToLoadChatText = "Couldn't load the chat. Either the link is expired or is missing some information...",
    somethingWrongText = "Something went wrong...",
    noSurveyChosenText = "No survey was chosen",
    surveyAlreadyCompetedText = "You have already completed this survey",
    noPublishedSurvey = "Sorry, I couldn't find any available surveys",
}

export enum ENUM_PT_STRINGS {
    language = "Língua",
    privacyNotice = "Por favor tome um momento para rever a nossa política de privacidade, antes de preencher o questionário.",
    startButtonText = "Iniciar",
    sendButtonText = "send",
    skipButtonText = "skip",
    restartButtonText = "Reiniciar",
    continueButtonText = "Continuar",
    endButtonText = "Done",
    endScreenButtonText = "Show Chat",
    doneConversation = "Parece que já estavamos a ter esta conversa ...",
    endScreenText = "Pode agora fechar esta página 😊",
    consentText = "* Ao clicar Iniciar, consente que esta informado e deseja responder ao questionário.",
    cookieText = "Hi! We'd like to use cookies to enhance your experience, but we need your consent to do so.",
    readMoreButtonText = "Read More",
    cookieAgreeButton = "Agree",
    wrongLinkText = "Sorry, either the link is expired or is missing some information...",
    unableToLoadChatText = "Couldn't load the chat. Either the link is expired or is missing some information...",
    somethingWrongText = "Something went wrong...",
    noSurveyChosenText = "No survey was chosen",
    surveyAlreadyCompetedText = "You have already completed this survey",
    noPublishedSurvey = "Sorry, I couldn't find any available surveys",
}